//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.08 at 08:17:20 PM EEST 
//


package com.sorin.mobilecmd.xml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClientFile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClientFile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ClientFileID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Folder" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Recursive" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClientFile", namespace = "http://www.sorin.com/cmd", propOrder = {

})
public class ClientFile {

    @XmlElement(name = "ClientFileID", namespace = "http://www.sorin.com/cmd")
    protected int clientFileID;
    @XmlElement(name = "FilePath", namespace = "http://www.sorin.com/cmd", required = true)
    protected String filePath;
    @XmlElement(name = "Folder", namespace = "http://www.sorin.com/cmd")
    protected boolean folder;
    @XmlElement(name = "Recursive", namespace = "http://www.sorin.com/cmd")
    protected boolean recursive;

    /**
     * Gets the value of the clientFileID property.
     * 
     */
    public int getClientFileID() {
        return clientFileID;
    }

    /**
     * Sets the value of the clientFileID property.
     * 
     */
    public void setClientFileID(int value) {
        this.clientFileID = value;
    }

    /**
     * Gets the value of the filePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * Sets the value of the filePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilePath(String value) {
        this.filePath = value;
    }

    /**
     * Gets the value of the folder property.
     * 
     */
    public boolean isFolder() {
        return folder;
    }

    /**
     * Sets the value of the folder property.
     * 
     */
    public void setFolder(boolean value) {
        this.folder = value;
    }

    /**
     * Gets the value of the recursive property.
     * 
     */
    public boolean isRecursive() {
        return recursive;
    }

    /**
     * Sets the value of the recursive property.
     * 
     */
    public void setRecursive(boolean value) {
        this.recursive = value;
    }

}
