//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.08 at 08:17:20 PM EEST 
//


package com.sorin.mobilecmd.xml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Client complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Client">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ClientID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ComputerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IpAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AllowCommands" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Client", namespace = "http://www.sorin.com/cmd", propOrder = {

})
public class Client {

    @XmlElement(name = "ClientID", namespace = "http://www.sorin.com/cmd")
    protected int clientID;
    @XmlElement(name = "ComputerName", namespace = "http://www.sorin.com/cmd", required = true)
    protected String computerName;
    @XmlElement(name = "IpAddress", namespace = "http://www.sorin.com/cmd", required = true)
    protected String ipAddress;
    @XmlElement(name = "AllowCommands", namespace = "http://www.sorin.com/cmd")
    protected boolean allowCommands;

    /**
     * Gets the value of the clientID property.
     * 
     */
    public int getClientID() {
        return clientID;
    }

    /**
     * Sets the value of the clientID property.
     * 
     */
    public void setClientID(int value) {
        this.clientID = value;
    }

    /**
     * Gets the value of the computerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComputerName() {
        return computerName;
    }

    /**
     * Sets the value of the computerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComputerName(String value) {
        this.computerName = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpAddress(String value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the allowCommands property.
     * 
     */
    public boolean isAllowCommands() {
        return allowCommands;
    }

    /**
     * Sets the value of the allowCommands property.
     * 
     */
    public void setAllowCommands(boolean value) {
        this.allowCommands = value;
    }

}
